---
services:
    nginx-gate-auth:
        build: .
        ports:
        - "8081:8080"
        links:
        - test-host
        networks:
        - nginx_gate_network
        environment:
        - "FORWARD_HOST=172.20.0.1:4000"
        - "LISTEN_PORT=8080"
        - "METRICS_PATH=/metrics"
        volumes:
        - data:/tmp
        - data:/var/cache/nginx
    nginx-gate-no-auth:
        build: .
        ports:
        - "8082:8080"
        networks:
        - nginx_gate_network
        links:
        - test-host
        environment:
        - "FORWARD_HOST=172.20.0.1:4000"
        - "LISTEN_PORT=8080"
        - "METRICS_PATH=/metrics"
        - "BASIC_AUTH_DISABLE=true"
        volumes:
        - data:/tmp
        - data:/var/cache/nginx
    nginx-gate-no-metrics:
        build: .
        ports:
        - "8083:8080"
        networks:
        - nginx_gate_network
        links:
        - test-host
        environment:
        - "FORWARD_HOST=172.20.0.1:4000"
        - "LISTEN_PORT=8080"
        volumes:
        - data:/tmp
        - data:/var/cache/nginx
    test-host:
        image: nginx:stable-alpine3.17-slim
        networks:
        - nginx_gate_network
        ports:
        - 80

volumes:
    data:

networks:
  nginx_gate_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1 # this needs to match with FORWARD_HOST env variable.
